import Image from "next/image";

import type { Template, TemplateStyle } from "@/app/lib/templates";

// Generated by scripts/generate-template-previews.ts — one representative
// screenshot per style (all templates sharing a style look the same today).
const previewImageByStyle: Record<TemplateStyle, string> = {
  Minimalistisch: "/template-previews/minimalistisch.png",
  Modern: "/template-previews/modern.png",
  Kreativ: "/template-previews/kreativ.png",
  Klassisch: "/template-previews/klassisch.png",
};

export function TemplatePreview({ template }: { template: Template }) {
  return (
    <div className="relative h-40 w-full overflow-hidden bg-paper dark:bg-paper-dark">
      <Image
        src={previewImageByStyle[template.style]}
        alt={`Beispielvorschau im Stil ${template.style}`}
        fill
        sizes="(max-width: 640px) 90vw, 360px"
        className="object-cover object-top"
      />
    </div>
  );
}
